AllCops:
  NewCops: enable
  Exclude: 
  - test.rb
  
Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
